spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://42.193.102.174:3306/course_online?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: course
    password: course
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.course.server.mapper: trace
